spring:
  datasource:
    url: jdbc:postgresql://dbpostgresql-crn:5432/customer-risk-notifier
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
app:
  job:
    cron-customer-risk-calculation: 5 * * * * *
  file:
    location: /upload

#  0 8-20/1 * * *
#  */1 7-20 * * *